# Generated by Django 6.0.2 on 2026-02-17 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='discount',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
